/**
 * SONORA Seed Prototype Catalog
 * Authoritative Reference: PRD.md Section 11/12, MILESTONE 2A
 * 
 * Meaningful default catalog of 64 authorized demo tracks, 18 artists,
 * 12 albums, 4 curated playlists, 12 genres, and 8 moods.
 * All tracks are 100% playable via synthesized acoustic sound profiles
 * with zero unauthorized streaming scraping.
 */

import { Track, Artist, Album, Playlist, Genre, Mood, TrackRights } from './types';

export const DEMO_TRACK_RIGHTS: TrackRights = {
  canStream: true,
  canPreview: true,
  canDJ: true,
  canEdit: true,
  canRemix: true,
  attributionRequired: true,
  sourceTermsUrl: 'https://sonora.audio/terms/prototype-demo',
};

export const SEED_GENRES: Genre[] = [
  { id: 'ambient', name: 'Ambient & Drone', description: 'Expansive timbral fields, floating drones, and meditative acoustic geometry.', color: 'var(--color-accent-iris)' },
  { id: 'techno', name: 'Peak Techno', description: 'Relentless analog pulses, modular transients, and subterranean 4-on-the-floor energy.', color: 'var(--color-accent-cyan)' },
  { id: 'house', name: 'Deep House', description: 'Warm chords, shuffling swing rhythms, and hypnotic percussive grooves.', color: 'var(--color-accent-amber)' },
  { id: 'lofi', name: 'Chill & Lo-Fi', description: 'Tape saturation, nostalgic Rhodes progressions, and laid-back micro-grooves.', color: '#a78bfa' },
  { id: 'synthwave', name: 'Synthwave', description: 'Retro-futuristic analog arpeggios, neon horizons, and gated acoustic percussion.', color: '#f43f5e' },
  { id: 'cinematic', name: 'Cinematic Score', description: 'Dramatic orchestral swells, deep resonant sub-drones, and emotive harmonic narratives.', color: '#38bdf8' },
  { id: 'drumandbass', name: 'Drum & Bass', description: '174 BPM syncopated breakbeats, reese basslines, and hyper-kinetic soundscapes.', color: '#fb923c' },
  { id: 'minimal', name: 'Minimal & Micro', description: 'Subtle clicks, clinical micro-textures, and expansive dub reverberation.', color: '#94a3b8' },
  { id: 'classical', name: 'Neo-Classical', description: 'Felt piano resonances, harmonic string chords, and delicate acoustic textures.', color: '#e2e8f0' },
  { id: 'triphop', name: 'Downtempo & Trip-Hop', description: 'Smoky acoustic rhythms, vinyl dust, and slow-blooming melancholic chords.', color: '#c084fc' },
  { id: 'trance', name: 'Progressive Trance', description: 'Euphoric arpeggiated melodies, hypnotic builds, and soaring harmonic plateaus.', color: '#2dd4bf' },
  { id: 'experimental', name: 'Experimental Glitch', description: 'Deconstructed waveforms, granular distortion, and non-linear sonic structures.', color: '#f472b6' },
];

export const SEED_MOODS: Mood[] = [
  { id: 'meditative', name: 'Meditative', energy: 0.15 },
  { id: 'serene', name: 'Serene', energy: 0.30 },
  { id: 'nostalgic', name: 'Nostalgic', energy: 0.45 },
  { id: 'hypnotic', name: 'Hypnotic', energy: 0.60 },
  { id: 'driving', name: 'Driving', energy: 0.75 },
  { id: 'euphoric', name: 'Euphoric', energy: 0.85 },
  { id: 'kinetic', name: 'Kinetic', energy: 0.92 },
  { id: 'transcendent', name: 'Transcendent', energy: 0.98 },
];

export const SEED_ARTISTS: Artist[] = [
  { id: 'art-01', name: 'Aethelgard', genres: ['Ambient & Drone', 'Cinematic Score'], bio: 'Sound designer exploring deep acoustic resonance and space travel mythology.', location: 'Reykjavik' },
  { id: 'art-02', name: 'Cyan Horizon', genres: ['Peak Techno', 'Minimal & Micro'], bio: 'Modular synthesizer pioneer engineering high-pressure acoustic environments.', location: 'Berlin' },
  { id: 'art-03', name: 'Kuroshio Drift', genres: ['Deep House', 'Downtempo & Trip-Hop'], bio: 'Deep water grooves and analog warmth inspired by oceanic currents.', location: 'Tokyo' },
  { id: 'art-04', name: 'Subatomic Echo', genres: ['Minimal & Micro', 'Peak Techno'], bio: 'Microscopic frequency architecture and surgical bass dynamics.', location: 'Bristol' },
  { id: 'art-05', name: 'Solaris Resonance', genres: ['Synthwave', 'Progressive Trance'], bio: 'Vintage analog hardware collector crafting widescreen retro-futuristic soundscapes.', location: 'Los Angeles' },
  { id: 'art-06', name: 'Nadia Vance', genres: ['Neo-Classical', 'Ambient & Drone'], bio: 'Acoustic pianist fusing felt keyboard mechanics with granular synthesis.', location: 'Montreal' },
  { id: 'art-07', name: 'Vektor Orbit', genres: ['Drum & Bass', 'Peak Techno'], bio: 'Fast breakbeat syncopation and modulated reese bass engineering.', location: 'London' },
  { id: 'art-08', name: 'Monolith 9', genres: ['Peak Techno', 'Experimental Glitch'], bio: 'Industrial percussion, distorted overtones, and tectonic low-end force.', location: 'Detroit' },
  { id: 'art-09', name: 'Velvet Shimmer', genres: ['Chill & Lo-Fi', 'Downtempo & Trip-Hop'], bio: 'Tape loops, vinyl dust, and late-night nocturnal jazz harmonies.', location: 'Paris' },
  { id: 'art-10', name: 'Hesperus', genres: ['Cinematic Score', 'Ambient & Drone'], bio: 'Film composer crafting vast dynamic soundfields for deep contemplation.', location: 'Vienna' },
  { id: 'art-11', name: 'Kalliope', genres: ['Deep House', 'Progressive Trance'], bio: 'Melodic house architect merging hypnotic percussion with vocal atmosphere.', location: 'Stockholm' },
  { id: 'art-12', name: 'Prism Architecture', genres: ['Experimental Glitch', 'Minimal & Micro'], bio: 'Algorithmic sound art deconstructing stereo space and time-domain signals.', location: 'Amsterdam' },
  { id: 'art-13', name: 'Apex Wave', genres: ['Synthwave', 'Drum & Bass'], bio: 'High-octane neon propulsion with searing lead synths and heavy breaks.', location: 'Seattle' },
  { id: 'art-14', name: 'Equinox Field', genres: ['Ambient & Drone', 'Neo-Classical'], bio: 'Binaural field recordings and harmonic drone chambers.', location: 'Oslo' },
  { id: 'art-15', name: 'Basalt Audio', genres: ['Peak Techno', 'Deep House'], bio: 'Stripped-back dub techno with organic analog warmth.', location: 'Tbilisi' },
  { id: 'art-16', name: 'Lunaire Beats', genres: ['Chill & Lo-Fi', 'Downtempo & Trip-Hop'], bio: 'Warm SP-404 grooves and dusty acoustic basslines.', location: 'Melbourne' },
  { id: 'art-17', name: 'Astral Continuum', genres: ['Progressive Trance', 'Synthwave'], bio: 'Epic arpeggios and cosmic uplifting harmonics.', location: 'Sydney' },
  { id: 'art-18', name: 'Zero Horizon', genres: ['Cinematic Score', 'Experimental Glitch'], bio: 'Post-digital ambient and orchestral dissonance.', location: 'Zurich' },
];

export const SEED_ALBUMS: Album[] = [
  { id: 'alb-01', title: 'Chronicles of the Void', artistId: 'art-01', artistName: 'Aethelgard', releaseYear: 2025, genre: 'Ambient & Drone', trackIds: ['track-01', 'track-02', 'track-03', 'track-04'] },
  { id: 'alb-02', title: 'Sub-Bass Topography', artistId: 'art-02', artistName: 'Cyan Horizon', releaseYear: 2025, genre: 'Peak Techno', trackIds: ['track-05', 'track-06', 'track-07', 'track-08'] },
  { id: 'alb-03', title: 'Oceanic Frequencies', artistId: 'art-03', artistName: 'Kuroshio Drift', releaseYear: 2024, genre: 'Deep House', trackIds: ['track-09', 'track-10', 'track-11', 'track-12'] },
  { id: 'alb-04', title: 'Quantum Grain', artistId: 'art-04', artistName: 'Subatomic Echo', releaseYear: 2025, genre: 'Minimal & Micro', trackIds: ['track-13', 'track-14', 'track-15', 'track-16'] },
  { id: 'alb-05', title: 'Neon Twilight', artistId: 'art-05', artistName: 'Solaris Resonance', releaseYear: 2025, genre: 'Synthwave', trackIds: ['track-17', 'track-18', 'track-19', 'track-20'] },
  { id: 'alb-06', title: 'Felt & Wire', artistId: 'art-06', artistName: 'Nadia Vance', releaseYear: 2024, genre: 'Neo-Classical', trackIds: ['track-21', 'track-22', 'track-23', 'track-24'] },
  { id: 'alb-07', title: 'Mach Velocity', artistId: 'art-07', artistName: 'Vektor Orbit', releaseYear: 2025, genre: 'Drum & Bass', trackIds: ['track-25', 'track-26', 'track-27', 'track-28'] },
  { id: 'alb-08', title: 'Dark Matter Engine', artistId: 'art-08', artistName: 'Monolith 9', releaseYear: 2025, genre: 'Peak Techno', trackIds: ['track-29', 'track-30', 'track-31', 'track-32'] },
  { id: 'alb-09', title: 'Midnight Tape Cassette', artistId: 'art-09', artistName: 'Velvet Shimmer', releaseYear: 2024, genre: 'Chill & Lo-Fi', trackIds: ['track-33', 'track-34', 'track-35', 'track-36'] },
  { id: 'alb-10', title: 'Interstellar Overture', artistId: 'art-10', artistName: 'Hesperus', releaseYear: 2025, genre: 'Cinematic Score', trackIds: ['track-37', 'track-38', 'track-39', 'track-40'] },
  { id: 'alb-11', title: 'Resonant Sanctuary', artistId: 'art-11', artistName: 'Kalliope', releaseYear: 2025, genre: 'Deep House', trackIds: ['track-41', 'track-42', 'track-43', 'track-44'] },
  { id: 'alb-12', title: 'Fractal Decomposition', artistId: 'art-12', artistName: 'Prism Architecture', releaseYear: 2025, genre: 'Experimental Glitch', trackIds: ['track-45', 'track-46', 'track-47', 'track-48'] },
];

export const SEED_TRACKS: Track[] = [
  // --- AMBIENT & DRONE (Tracks 1-8) ---
  {
    id: 'track-01',
    title: 'Event Horizon Ingress',
    artistId: 'art-01',
    artistName: 'Aethelgard',
    albumId: 'alb-01',
    albumName: 'Chronicles of the Void',
    duration: 380,
    genre: 'Ambient & Drone',
    moods: ['Meditative', 'Transcendent'],
    bpm: 72,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Aethelgard', license: 'CC BY 4.0', notes: 'SONORA Acoustic Lab Demo' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-02',
    title: 'Pillars of Cyan Light',
    artistId: 'art-01',
    artistName: 'Aethelgard',
    albumId: 'alb-01',
    albumName: 'Chronicles of the Void',
    duration: 320,
    genre: 'Ambient & Drone',
    moods: ['Serene', 'Meditative'],
    bpm: 68,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Aethelgard', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-03',
    title: 'Acoustic Singularity',
    artistId: 'art-01',
    artistName: 'Aethelgard',
    albumId: 'alb-01',
    albumName: 'Chronicles of the Void',
    duration: 410,
    genre: 'Ambient & Drone',
    moods: ['Hypnotic', 'Transcendent'],
    bpm: 75,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Aethelgard', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-04',
    title: 'Solar Wind Lullaby',
    artistId: 'art-01',
    artistName: 'Aethelgard',
    albumId: 'alb-01',
    albumName: 'Chronicles of the Void',
    duration: 295,
    genre: 'Ambient & Drone',
    moods: ['Serene'],
    bpm: 64,
    key: '10A', // Bm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Aethelgard', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-05',
    title: 'Sub-Zero Resonance',
    artistId: 'art-14',
    artistName: 'Equinox Field',
    duration: 345,
    genre: 'Ambient & Drone',
    moods: ['Meditative', 'Hypnotic'],
    bpm: 70,
    key: '11A', // F#m
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Equinox Field', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-06',
    title: 'Chamber of Whispering Dust',
    artistId: 'art-14',
    artistName: 'Equinox Field',
    duration: 360,
    genre: 'Ambient & Drone',
    moods: ['Serene'],
    bpm: 65,
    key: '12A', // Dbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Equinox Field', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-07',
    title: 'Orbital Descent in Iris',
    artistId: 'art-18',
    artistName: 'Zero Horizon',
    duration: 310,
    genre: 'Ambient & Drone',
    moods: ['Hypnotic', 'Meditative'],
    bpm: 74,
    key: '1A', // Abm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Zero Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-08',
    title: 'Silent Aurora Matrix',
    artistId: 'art-18',
    artistName: 'Zero Horizon',
    duration: 390,
    genre: 'Ambient & Drone',
    moods: ['Transcendent'],
    bpm: 70,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Zero Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },

  // --- PEAK TECHNO (Tracks 9-16) ---
  {
    id: 'track-09',
    title: 'Subterranean Pressure Wave',
    artistId: 'art-02',
    artistName: 'Cyan Horizon',
    albumId: 'alb-02',
    albumName: 'Sub-Bass Topography',
    duration: 395,
    genre: 'Peak Techno',
    moods: ['Driving', 'Kinetic'],
    bpm: 132,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Cyan Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-10',
    title: 'Cyan Ion Accelerator',
    artistId: 'art-02',
    artistName: 'Cyan Horizon',
    albumId: 'alb-02',
    albumName: 'Sub-Bass Topography',
    duration: 370,
    genre: 'Peak Techno',
    moods: ['Driving', 'Hypnotic'],
    bpm: 134,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Cyan Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-11',
    title: 'Modular Kinetic Force',
    artistId: 'art-02',
    artistName: 'Cyan Horizon',
    albumId: 'alb-02',
    albumName: 'Sub-Bass Topography',
    duration: 360,
    genre: 'Peak Techno',
    moods: ['Kinetic', 'Driving'],
    bpm: 135,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Cyan Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-12',
    title: 'Sub-40Hz Displacement',
    artistId: 'art-02',
    artistName: 'Cyan Horizon',
    albumId: 'alb-02',
    albumName: 'Sub-Bass Topography',
    duration: 410,
    genre: 'Peak Techno',
    moods: ['Hypnotic'],
    bpm: 130,
    key: '6A', // Gm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Cyan Horizon', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-13',
    title: 'Forged in Obsidian',
    artistId: 'art-08',
    artistName: 'Monolith 9',
    albumId: 'alb-08',
    albumName: 'Dark Matter Engine',
    duration: 385,
    genre: 'Peak Techno',
    moods: ['Driving', 'Kinetic'],
    bpm: 136,
    key: '5A', // Cm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Monolith 9', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-14',
    title: 'Industrial Pulse Vector',
    artistId: 'art-08',
    artistName: 'Monolith 9',
    albumId: 'alb-08',
    albumName: 'Dark Matter Engine',
    duration: 350,
    genre: 'Peak Techno',
    moods: ['Kinetic'],
    bpm: 138,
    key: '4A', // Fm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Monolith 9', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-15',
    title: 'Tectonic Basalt Groove',
    artistId: 'art-15',
    artistName: 'Basalt Audio',
    duration: 420,
    genre: 'Peak Techno',
    moods: ['Hypnotic', 'Driving'],
    bpm: 128,
    key: '3A', // Bbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Basalt Audio', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },
  {
    id: 'track-16',
    title: 'Overdriven Resonator 99',
    artistId: 'art-15',
    artistName: 'Basalt Audio',
    duration: 340,
    genre: 'Peak Techno',
    moods: ['Kinetic'],
    bpm: 133,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Basalt Audio', license: 'CC BY 4.0' },
    demoProfile: { style: 'techno' },
  },

  // --- DEEP HOUSE (Tracks 17-24) ---
  {
    id: 'track-17',
    title: 'Amber Swell',
    artistId: 'art-03',
    artistName: 'Kuroshio Drift',
    albumId: 'alb-03',
    albumName: 'Oceanic Frequencies',
    duration: 360,
    genre: 'Deep House',
    moods: ['Hypnotic', 'Euphoric'],
    bpm: 124,
    key: '8B', // C major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Kuroshio Drift', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-18',
    title: 'Currents of Shinjuku',
    artistId: 'art-03',
    artistName: 'Kuroshio Drift',
    albumId: 'alb-03',
    albumName: 'Oceanic Frequencies',
    duration: 345,
    genre: 'Deep House',
    moods: ['Driving', 'Euphoric'],
    bpm: 123,
    key: '9B', // G major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Kuroshio Drift', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-19',
    title: 'Pacific Thermal Plume',
    artistId: 'art-03',
    artistName: 'Kuroshio Drift',
    albumId: 'alb-03',
    albumName: 'Oceanic Frequencies',
    duration: 390,
    genre: 'Deep House',
    moods: ['Hypnotic'],
    bpm: 122,
    key: '7B', // F major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Kuroshio Drift', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-20',
    title: 'Tide Gauge Harmonics',
    artistId: 'art-03',
    artistName: 'Kuroshio Drift',
    albumId: 'alb-03',
    albumName: 'Oceanic Frequencies',
    duration: 330,
    genre: 'Deep House',
    moods: ['Serene', 'Euphoric'],
    bpm: 125,
    key: '10B', // D major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Kuroshio Drift', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-21',
    title: 'Ethereal Sanctuary',
    artistId: 'art-11',
    artistName: 'Kalliope',
    albumId: 'alb-11',
    albumName: 'Resonant Sanctuary',
    duration: 375,
    genre: 'Deep House',
    moods: ['Euphoric', 'Transcendent'],
    bpm: 124,
    key: '11B', // A major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Kalliope', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-22',
    title: 'Sunlight Through Stained Glass',
    artistId: 'art-11',
    artistName: 'Kalliope',
    albumId: 'alb-11',
    albumName: 'Resonant Sanctuary',
    duration: 350,
    genre: 'Deep House',
    moods: ['Euphoric'],
    bpm: 125,
    key: '12B', // E major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Kalliope', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-23',
    title: 'Velvet Groove Protocol',
    artistId: 'art-11',
    artistName: 'Kalliope',
    albumId: 'alb-11',
    albumName: 'Resonant Sanctuary',
    duration: 380,
    genre: 'Deep House',
    moods: ['Hypnotic', 'Driving'],
    bpm: 122,
    key: '1B', // B major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Kalliope', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },
  {
    id: 'track-24',
    title: 'Dusk Over Baltic Waters',
    artistId: 'art-11',
    artistName: 'Kalliope',
    albumId: 'alb-11',
    albumName: 'Resonant Sanctuary',
    duration: 365,
    genre: 'Deep House',
    moods: ['Serene', 'Euphoric'],
    bpm: 123,
    key: '2B', // F# major
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Kalliope', license: 'CC BY 4.0' },
    demoProfile: { style: 'house' },
  },

  // --- CHILL & LO-FI (Tracks 25-32) ---
  {
    id: 'track-25',
    title: 'Midnight Rooftop Coffee',
    artistId: 'art-09',
    artistName: 'Velvet Shimmer',
    albumId: 'alb-09',
    albumName: 'Midnight Tape Cassette',
    duration: 195,
    genre: 'Chill & Lo-Fi',
    moods: ['Nostalgic', 'Serene'],
    bpm: 82,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Velvet Shimmer', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-26',
    title: 'Montmartre Rain Drops',
    artistId: 'art-09',
    artistName: 'Velvet Shimmer',
    albumId: 'alb-09',
    albumName: 'Midnight Tape Cassette',
    duration: 210,
    genre: 'Chill & Lo-Fi',
    moods: ['Nostalgic'],
    bpm: 80,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Velvet Shimmer', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-27',
    title: 'Dusty Rhodes Reverie',
    artistId: 'art-09',
    artistName: 'Velvet Shimmer',
    albumId: 'alb-09',
    albumName: 'Midnight Tape Cassette',
    duration: 185,
    genre: 'Chill & Lo-Fi',
    moods: ['Serene', 'Nostalgic'],
    bpm: 84,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Velvet Shimmer', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-28',
    title: 'Cassette Tape Flutters',
    artistId: 'art-09',
    artistName: 'Velvet Shimmer',
    albumId: 'alb-09',
    albumName: 'Midnight Tape Cassette',
    duration: 220,
    genre: 'Chill & Lo-Fi',
    moods: ['Nostalgic'],
    bpm: 78,
    key: '6A', // Gm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Velvet Shimmer', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-29',
    title: 'Subway Headphone Dreams',
    artistId: 'art-16',
    artistName: 'Lunaire Beats',
    duration: 205,
    genre: 'Chill & Lo-Fi',
    moods: ['Serene', 'Nostalgic'],
    bpm: 83,
    key: '5A', // Cm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Lunaire Beats', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-30',
    title: 'Wabi-Sabi Kitchen Table',
    artistId: 'art-16',
    artistName: 'Lunaire Beats',
    duration: 190,
    genre: 'Chill & Lo-Fi',
    moods: ['Meditative'],
    bpm: 76,
    key: '4A', // Fm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Lunaire Beats', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-31',
    title: 'Analog Vinyl Whispers',
    artistId: 'art-16',
    artistName: 'Lunaire Beats',
    duration: 235,
    genre: 'Chill & Lo-Fi',
    moods: ['Nostalgic'],
    bpm: 85,
    key: '3A', // Bbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Lunaire Beats', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },
  {
    id: 'track-32',
    title: 'Paper Lantern Glow',
    artistId: 'art-16',
    artistName: 'Lunaire Beats',
    duration: 175,
    genre: 'Chill & Lo-Fi',
    moods: ['Serene'],
    bpm: 81,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Lunaire Beats', license: 'CC BY 4.0' },
    demoProfile: { style: 'lofi' },
  },

  // --- SYNTHWAVE & RETRO (Tracks 33-40) ---
  {
    id: 'track-33',
    title: 'Pacific Coast Highway 1984',
    artistId: 'art-05',
    artistName: 'Solaris Resonance',
    albumId: 'alb-05',
    albumName: 'Neon Twilight',
    duration: 275,
    genre: 'Synthwave',
    moods: ['Driving', 'Nostalgic'],
    bpm: 118,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Solaris Resonance', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-34',
    title: 'Cybernetic Sunset Boulevard',
    artistId: 'art-05',
    artistName: 'Solaris Resonance',
    albumId: 'alb-05',
    albumName: 'Neon Twilight',
    duration: 290,
    genre: 'Synthwave',
    moods: ['Euphoric', 'Driving'],
    bpm: 120,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Solaris Resonance', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-35',
    title: 'Vector Laser Grid',
    artistId: 'art-05',
    artistName: 'Solaris Resonance',
    albumId: 'alb-05',
    albumName: 'Neon Twilight',
    duration: 260,
    genre: 'Synthwave',
    moods: ['Kinetic', 'Driving'],
    bpm: 122,
    key: '10A', // Bm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Solaris Resonance', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-36',
    title: 'Tokyo Turbochargers',
    artistId: 'art-05',
    artistName: 'Solaris Resonance',
    albumId: 'alb-05',
    albumName: 'Neon Twilight',
    duration: 310,
    genre: 'Synthwave',
    moods: ['Kinetic', 'Driving'],
    bpm: 124,
    key: '11A', // F#m
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Solaris Resonance', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-37',
    title: 'Redline Skyline 1989',
    artistId: 'art-13',
    artistName: 'Apex Wave',
    duration: 285,
    genre: 'Synthwave',
    moods: ['Kinetic', 'Driving'],
    bpm: 126,
    key: '12A', // Dbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Apex Wave', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-38',
    title: 'Outrun the Solar Flare',
    artistId: 'art-13',
    artistName: 'Apex Wave',
    duration: 305,
    genre: 'Synthwave',
    moods: ['Driving', 'Euphoric'],
    bpm: 125,
    key: '1A', // Abm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Apex Wave', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-39',
    title: 'Arcade Odyssey at Midnight',
    artistId: 'art-17',
    artistName: 'Astral Continuum',
    duration: 295,
    genre: 'Synthwave',
    moods: ['Euphoric'],
    bpm: 120,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Astral Continuum', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },
  {
    id: 'track-40',
    title: 'Cassiopeia Expressway',
    artistId: 'art-17',
    artistName: 'Astral Continuum',
    duration: 320,
    genre: 'Synthwave',
    moods: ['Driving'],
    bpm: 122,
    key: '3A', // Bbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Astral Continuum', license: 'CC BY 4.0' },
    demoProfile: { style: 'synthwave' },
  },

  // --- CINEMATIC SCORE (Tracks 41-48) ---
  {
    id: 'track-41',
    title: 'Descent to the Oceanic Trenches',
    artistId: 'art-10',
    artistName: 'Hesperus',
    albumId: 'alb-10',
    albumName: 'Interstellar Overture',
    duration: 415,
    genre: 'Cinematic Score',
    moods: ['Transcendent', 'Hypnotic'],
    bpm: 65,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Hesperus', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-42',
    title: 'The Titan Atmospheric Probe',
    artistId: 'art-10',
    artistName: 'Hesperus',
    albumId: 'alb-10',
    albumName: 'Interstellar Overture',
    duration: 390,
    genre: 'Cinematic Score',
    moods: ['Hypnotic', 'Transcendent'],
    bpm: 70,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Hesperus', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-43',
    title: 'Supernova Remnant Horizon',
    artistId: 'art-10',
    artistName: 'Hesperus',
    albumId: 'alb-10',
    albumName: 'Interstellar Overture',
    duration: 440,
    genre: 'Cinematic Score',
    moods: ['Transcendent'],
    bpm: 60,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Hesperus', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-44',
    title: 'Acoustic Monument of Glass',
    artistId: 'art-10',
    artistName: 'Hesperus',
    albumId: 'alb-10',
    albumName: 'Interstellar Overture',
    duration: 360,
    genre: 'Cinematic Score',
    moods: ['Serene', 'Meditative'],
    bpm: 68,
    key: '6A', // Gm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Hesperus', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-45',
    title: 'Glacial Calving Ceremony',
    artistId: 'art-06',
    artistName: 'Nadia Vance',
    albumId: 'alb-06',
    albumName: 'Felt & Wire',
    duration: 310,
    genre: 'Neo-Classical',
    moods: ['Serene', 'Nostalgic'],
    bpm: 72,
    key: '5A', // Cm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Nadia Vance', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-46',
    title: 'Felt Piano in Empty Vault',
    artistId: 'art-06',
    artistName: 'Nadia Vance',
    albumId: 'alb-06',
    albumName: 'Felt & Wire',
    duration: 290,
    genre: 'Neo-Classical',
    moods: ['Meditative', 'Nostalgic'],
    bpm: 66,
    key: '4A', // Fm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Nadia Vance', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-47',
    title: 'String Resonance at Twilight',
    artistId: 'art-06',
    artistName: 'Nadia Vance',
    albumId: 'alb-06',
    albumName: 'Felt & Wire',
    duration: 330,
    genre: 'Neo-Classical',
    moods: ['Serene'],
    bpm: 74,
    key: '3A', // Bbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Nadia Vance', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },
  {
    id: 'track-48',
    title: 'Bowing the Steel Cable',
    artistId: 'art-06',
    artistName: 'Nadia Vance',
    albumId: 'alb-06',
    albumName: 'Felt & Wire',
    duration: 375,
    genre: 'Neo-Classical',
    moods: ['Transcendent'],
    bpm: 68,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2024,
    attribution: { artist: 'Nadia Vance', license: 'CC BY 4.0' },
    demoProfile: { style: 'cinematic' },
  },

  // --- DRUM & BASS (Tracks 49-56) ---
  {
    id: 'track-49',
    title: 'Mach 3 Sub Orbital',
    artistId: 'art-07',
    artistName: 'Vektor Orbit',
    albumId: 'alb-07',
    albumName: 'Mach Velocity',
    duration: 320,
    genre: 'Drum & Bass',
    moods: ['Kinetic', 'Driving'],
    bpm: 174,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Vektor Orbit', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-50',
    title: 'Reese Bass Metamorphosis',
    artistId: 'art-07',
    artistName: 'Vektor Orbit',
    albumId: 'alb-07',
    albumName: 'Mach Velocity',
    duration: 310,
    genre: 'Drum & Bass',
    moods: ['Kinetic', 'Driving'],
    bpm: 175,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Vektor Orbit', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-51',
    title: 'Amen Quantum Flux',
    artistId: 'art-07',
    artistName: 'Vektor Orbit',
    albumId: 'alb-07',
    albumName: 'Mach Velocity',
    duration: 295,
    genre: 'Drum & Bass',
    moods: ['Kinetic'],
    bpm: 174,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Vektor Orbit', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-52',
    title: 'Liquid Silicon Drift',
    artistId: 'art-07',
    artistName: 'Vektor Orbit',
    albumId: 'alb-07',
    albumName: 'Mach Velocity',
    duration: 340,
    genre: 'Drum & Bass',
    moods: ['Euphoric', 'Kinetic'],
    bpm: 172,
    key: '10A', // Bm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Vektor Orbit', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-53',
    title: 'Gravity Assist Velocity',
    artistId: 'art-13',
    artistName: 'Apex Wave',
    duration: 300,
    genre: 'Drum & Bass',
    moods: ['Kinetic'],
    bpm: 176,
    key: '11A', // F#m
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Apex Wave', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-54',
    title: 'Sub-Sonic Shockfront',
    artistId: 'art-13',
    artistName: 'Apex Wave',
    duration: 330,
    genre: 'Drum & Bass',
    moods: ['Driving', 'Kinetic'],
    bpm: 174,
    key: '12A', // Dbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Apex Wave', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-55',
    title: 'Perimeter Boundary Break',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    duration: 285,
    genre: 'Drum & Bass',
    moods: ['Kinetic'],
    bpm: 170,
    key: '1A', // Abm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },
  {
    id: 'track-56',
    title: 'Thermal Compression Blast',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    duration: 315,
    genre: 'Drum & Bass',
    moods: ['Kinetic', 'Driving'],
    bpm: 174,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'drumandbass' },
  },

  // --- MINIMAL, DOWNTEMPO & EXPERIMENTAL (Tracks 57-64) ---
  {
    id: 'track-57',
    title: 'Micro-Structure Geometry',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    albumId: 'alb-04',
    albumName: 'Quantum Grain',
    duration: 370,
    genre: 'Minimal & Micro',
    moods: ['Hypnotic', 'Meditative'],
    bpm: 125,
    key: '8A', // Am
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-58',
    title: 'Dub Dispersion Chamber',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    albumId: 'alb-04',
    albumName: 'Quantum Grain',
    duration: 390,
    genre: 'Minimal & Micro',
    moods: ['Hypnotic'],
    bpm: 124,
    key: '9A', // Em
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-59',
    title: 'Click-Train Modulation',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    albumId: 'alb-04',
    albumName: 'Quantum Grain',
    duration: 345,
    genre: 'Minimal & Micro',
    moods: ['Hypnotic', 'Driving'],
    bpm: 126,
    key: '7A', // Dm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-60',
    title: 'Sub-Surface Acoustic Cavern',
    artistId: 'art-04',
    artistName: 'Subatomic Echo',
    albumId: 'alb-04',
    albumName: 'Quantum Grain',
    duration: 410,
    genre: 'Minimal & Micro',
    moods: ['Meditative'],
    bpm: 122,
    key: '6A', // Gm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Subatomic Echo', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-61',
    title: 'Granular Lattice Fracture',
    artistId: 'art-12',
    artistName: 'Prism Architecture',
    albumId: 'alb-12',
    albumName: 'Fractal Decomposition',
    duration: 320,
    genre: 'Experimental Glitch',
    moods: ['Hypnotic', 'Transcendent'],
    bpm: 110,
    key: '5A', // Cm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Prism Architecture', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-62',
    title: 'Deconstructed Time-Domain Shard',
    artistId: 'art-12',
    artistName: 'Prism Architecture',
    albumId: 'alb-12',
    albumName: 'Fractal Decomposition',
    duration: 340,
    genre: 'Experimental Glitch',
    moods: ['Kinetic'],
    bpm: 130,
    key: '4A', // Fm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Prism Architecture', license: 'CC BY 4.0' },
    demoProfile: { style: 'minimal' },
  },
  {
    id: 'track-63',
    title: 'Acoustic Prism Reflection',
    artistId: 'art-12',
    artistName: 'Prism Architecture',
    albumId: 'alb-12',
    albumName: 'Fractal Decomposition',
    duration: 360,
    genre: 'Experimental Glitch',
    moods: ['Transcendent'],
    bpm: 115,
    key: '3A', // Bbm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Prism Architecture', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
  {
    id: 'track-64',
    title: 'Echoes of the Transfinite',
    artistId: 'art-12',
    artistName: 'Prism Architecture',
    albumId: 'alb-12',
    albumName: 'Fractal Decomposition',
    duration: 405,
    genre: 'Experimental Glitch',
    moods: ['Meditative', 'Transcendent'],
    bpm: 95,
    key: '2A', // Ebm
    source: 'demo',
    isPlayable: true,
    isLocal: false,
    releaseYear: 2025,
    attribution: { artist: 'Prism Architecture', license: 'CC BY 4.0' },
    demoProfile: { style: 'ambient' },
  },
];

// Ensure all authorized demo tracks are explicitly rights-adorned for full capability verification
SEED_TRACKS.forEach((t) => {
  if (!t.rights) {
    t.rights = DEMO_TRACK_RIGHTS;
  }
});

export const SEED_PLAYLISTS: Playlist[] = [
  {
    id: 'pl-01',
    name: 'Deep Space Resonance',
    description: 'Immense cosmic drones, meditative timbral fields, and zero-gravity acoustic architecture.',
    trackIds: ['track-01', 'track-02', 'track-03', 'track-04', 'track-05', 'track-07', 'track-41', 'track-42'],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-02-15T00:00:00Z',
  },
  {
    id: 'pl-02',
    name: 'Peak Time Energy',
    description: 'Subterranean 4-on-the-floor kick pressure, raw analog modular sweeps, and dynamic club power.',
    trackIds: ['track-09', 'track-10', 'track-11', 'track-13', 'track-14', 'track-17', 'track-21', 'track-49'],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-02-20T00:00:00Z',
  },
  {
    id: 'pl-03',
    name: 'Late Night Coordinates',
    description: 'Warm dusty vinyl crackle, nostalgic electric keys, and slow-breathing nocturnal beat sessions.',
    trackIds: ['track-25', 'track-26', 'track-27', 'track-28', 'track-29', 'track-30', 'track-45', 'track-46'],
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2025-02-25T00:00:00Z',
  },
  {
    id: 'pl-04',
    name: 'Kinetic Horizon',
    description: '174 BPM syncopated breakbeats, neon synthwave arpeggios, and hypersonic velocity.',
    trackIds: ['track-33', 'track-34', 'track-35', 'track-37', 'track-49', 'track-50', 'track-52', 'track-53'],
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-03-01T00:00:00Z',
  },
];
